# Generated by Django 3.2.12 on 2022-05-27 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('idAnime', models.TextField(primary_key=True, serialize=False, verbose_name='idAnime')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('formato', models.TextField(verbose_name='Formato')),
                ('nEpisodios', models.IntegerField(verbose_name='nEpisodios')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.TextField(primary_key=True, serialize=False, verbose_name='Genero')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField(verbose_name='idUsuario')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('idAnime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime', verbose_name='idAnime')),
            ],
            options={
                'ordering': ('idAnime', 'idUsuario'),
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(to='main.Genero'),
        ),
    ]
