# Generated by Django 3.2.5 on 2022-04-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_local', to='principal.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_visitante', to='principal.equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='partido',
            unique_together={('jornada', 'local', 'visitante')},
        ),
    ]
