# Generated by Django 3.2.12 on 2022-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('imagen', models.URLField(verbose_name='URL de Imagen')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
    ]
